development:
  SVN_User: fbeyer
  SVN_Password: Newton02
  Git_User: build
  Git_Password: build
  Jira_URL: https://jira.intuit.com/browse
  Project_Key_list: ['QBSE','QBE','QBUI']
  Fisheye_URL: https://jira-t:8443/fisheye/changelog/
  CollabNet_URL: https://qblab-svn.corp.intuit.net/viewvc/quickbase?view=revision


test:
  SVN_User: build
  SVN_Password: build
  Git_User: build
  Git_Password: build
  Jira_URL: https://jira.intuit.com/browse
  Project_Key_list: ['QBSE','QBE','QBUI']
  Fisheye_URL: https://jira-t:8443/fisheye/changelog/
  CollabNet_URL: https://qblab-svn.corp.intuit.net/viewvc/quickbase?view=revision


production:
  SVN_User: build
  SVN_Password: build
  Git_User: build
  Git_Password: build
  Jira_URL: https://jira.intuit.com/browse
  Project_Key_list: ['QBSE','QBE','QBUI']
  Fisheye_URL: https://jira-t:8443/fisheye/changelog/
  CollabNet_URL: https://qblab-svn.corp.intuit.net/viewvc/quickbase?view=revision